truncate table  mkn_ek_nov_2021_subs_BTSTRP;

begin
      for i in (
          select distinct market_key
          from dim_market 
          where market_key not in ('-99','ALL')
          order by market_key
       ) loop 
        insert into mkn_ek_nov_2021_subs_BTSTRP
        SELECT * FROM (
                        SELECT MARKET_KEY, BAN_KEY, SUBS_KEY, price_plan_key, 'CG' AS GROUP_IND, SAMPLE_N, REC_ID
                        FROM mkn_ek_nov_2021_month_cg_samp
                        WHERE market_key = i.market_key
                        UNION ALL
                        SELECT MARKET_KEY, BAN_KEY, SUBS_KEY, price_plan_key, 'TG' AS GROUP_IND, SAMPLE_N , REC_ID
                        FROM mkn_ek_nov_2021_month_tg_samp
                        WHERE market_key = i.market_key
                      )
        where 1=1;
        commit;              
        end loop;
end;

--Control-----------------------
select group_ind, sample_n, count (subs_key) as base, count (distinct subs_key) as base_un
from  mkn_ek_nov_2021_subs_BTSTRP
group by group_ind, sample_n
order by sample_n, group_ind
;      
      




create table mkn_ek_nov_2021_subs_BTSTRP
(
  MARKET_KEY CHAR(3),
  BAN_KEY NUMBER(9),
  SUBS_KEY   VARCHAR2(10),
  price_plan_key   VARCHAR2(9),
  --type_vse_old number,
  --lt VARCHAR2(9),
  GROUP_IND CHAR(2),
  SAMPLE_N NUMBER,
  REC_ID NUMBER
)
 compress parallel(degree 8) nologging 
PARTITION BY LIST (market_key)
--PARTITION TEMPLATE
(
PARTITION P_ABK VALUES ('ABK'),
PARTITION P_ANR VALUES ('ANR'),
PARTITION P_ARH VALUES ('ARH'),
PARTITION P_AST VALUES ('AST'),
PARTITION P_BAR VALUES ('BAR'),
PARTITION P_BGK VALUES ('BGK'),
PARTITION P_BIR VALUES ('BIR'),
PARTITION P_BLG VALUES ('BLG'),
PARTITION P_BRN VALUES ('BRN'),
PARTITION P_BUR VALUES ('BUR'),
PARTITION P_CHB VALUES ('CHB'),
PARTITION P_CHL VALUES ('CHL'),
PARTITION P_CHT VALUES ('CHT'),
PARTITION P_DTI VALUES ('DTI'),
PARTITION P_EKT VALUES ('EKT'),
PARTITION P_EST VALUES ('EST'),
PARTITION P_EXT VALUES ('EXT'),
PARTITION P_GAL VALUES ('GAL'),
PARTITION P_GRZ VALUES ('GRZ'),
PARTITION P_HBR VALUES ('HBR'),
PARTITION P_HMS VALUES ('HMS'),
PARTITION P_IGK VALUES ('IGK'),
PARTITION P_IKO VALUES ('IKO'),
PARTITION P_IRK VALUES ('IRK'),
PARTITION P_IVN VALUES ('IVN'),
PARTITION P_KC1 VALUES ('KC1'),
PARTITION P_KCH VALUES ('KCH'),
PARTITION P_KIR VALUES ('KIR'),
PARTITION P_KLG VALUES ('KLG'),
PARTITION P_KMR VALUES ('KMR'),
PARTITION P_KRD VALUES ('KRD'),
PARTITION P_KRG VALUES ('KRG'),
PARTITION P_KRL VALUES ('KRL'),
PARTITION P_KRS VALUES ('KRS'),
PARTITION P_KSK VALUES ('KSK'),
PARTITION P_KSM VALUES ('KSM'),
PARTITION P_KUR VALUES ('KUR'),
PARTITION P_KZL VALUES ('KZL'),
PARTITION P_KZN VALUES ('KZN'),
PARTITION P_LPK VALUES ('LPK'),
PARTITION P_MAH VALUES ('MAH'),
PARTITION P_MGD VALUES ('MGD'),
PARTITION P_MGN VALUES ('MGN'),
PARTITION P_MUR VALUES ('MUR'),
PARTITION P_NA1 VALUES ('NA1'),
PARTITION P_NAL VALUES ('NAL'),
PARTITION P_NNG VALUES ('NNG'),
PARTITION P_NOR VALUES ('NOR'),
PARTITION P_NSK VALUES ('NSK'),
PARTITION P_NTG VALUES ('NTG'),
PARTITION P_NZR VALUES ('NZR'),
PARTITION P_OMS VALUES ('OMS'),
PARTITION P_ORB VALUES ('ORB'),
PARTITION P_ORL VALUES ('ORL'),
PARTITION P_PNZ VALUES ('PNZ'),
PARTITION P_PPK VALUES ('PPK'),
PARTITION P_PRM VALUES ('PRM'),
PARTITION P_PSK VALUES ('PSK'),
PARTITION P_RND VALUES ('RND'),
PARTITION P_RZN VALUES ('RZN'),
PARTITION P_SAM VALUES ('SAM'),
PARTITION P_SCH VALUES ('SCH'),
PARTITION P_SHL VALUES ('SHL'),
PARTITION P_SKH VALUES ('SKH'),
PARTITION P_SMF VALUES ('SMF'),
PARTITION P_SML VALUES ('SML'),
PARTITION P_SPB VALUES ('SPB'),
PARTITION P_SRN VALUES ('SRN'),
PARTITION P_SRT VALUES ('SRT'),
PARTITION P_STK VALUES ('STK'),
PARTITION P_STR VALUES ('STR'),
PARTITION P_STV VALUES ('STV'),
PARTITION P_TMB VALUES ('TMB'),
PARTITION P_TMS VALUES ('TMS'),
PARTITION P_TOL VALUES ('TOL'),
PARTITION P_TUL VALUES ('TUL'),
PARTITION P_TUM VALUES ('TUM'),
PARTITION P_TVR VALUES ('TVR'),
PARTITION P_UFA VALUES ('UFA'),
PARTITION P_ULN VALUES ('ULN'),
PARTITION P_USH VALUES ('USH'),
PARTITION P_VIP VALUES ('VIP'),
PARTITION P_VLA VALUES ('VLA'),
PARTITION P_VLD VALUES ('VLD'),
PARTITION P_VLG VALUES ('VLG'),
PARTITION P_VLK VALUES ('VLK'),
PARTITION P_VNG VALUES ('VNG'),
PARTITION P_VOL VALUES ('VOL'),
PARTITION P_VRN VALUES ('VRN'),
PARTITION P_YAK VALUES ('YAK'),
PARTITION P_YAM VALUES ('YAM'),
PARTITION P_YRL VALUES ('YRL'),
PARTITION P_DEF VALUES (default)
)
;
