{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6c1026c9-883a-4cb7-9f31-7733f158c33e",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import psycopg2\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.ticker as ticker\n",
    "import numpy as np\n",
    "import seaborn as sns \n",
    "import statsmodels.stats.proportion as proportion\n",
    "from scipy.stats import ttest_ind,mannwhitneyu,shapiro,norm\n",
    "from statsmodels.stats.weightstats import ztest\n",
    "from tqdm import tqdm\n",
    "import timeit\n",
    "from scipy import stats\n",
    "import math\n",
    "from datetime import date, datetime, timedelta\n",
    "import time\n",
    "from sqlalchemy import create_engine, text\n",
    "from sqlalchemy.orm import sessionmaker\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "import clickhouse_connect  \n",
    "\n",
    "from credential import postgres_secret,clickhouse_dwh_secret\n",
    "\n",
    "def get_engine(user):\n",
    "    if user == postgres_secret['user']:\n",
    "        db_name = postgres_secret['db_name']\n",
    "        password = postgres_secret['password']\n",
    "        host = postgres_secret['host']\n",
    "        engine = create_engine(f'postgresql://{user}:{password}@{host}:6432/{db_name}')\n",
    "    elif user == clickhouse_dwh_secret['user']:\n",
    "            db_name = clickhouse_dwh_secret['db_name'] \n",
    "            password = clickhouse_dwh_secret['password']\n",
    "            host = clickhouse_dwh_secret['host']\n",
    "            engine = create_engine(f'clickhouse://{user}:{password}@{host}:8123/{db_name}')\n",
    "    return engine\n",
    "    \n",
    "connection_clickhouse = clickhouse_connect.get_client(\n",
    "    host = clickhouse_dwh_secret['host'],\n",
    "    port= '8123',\n",
    "    username = clickhouse_dwh_secret['user'],\n",
    "    password = clickhouse_dwh_secret['password'],\n",
    "    database='datamarts'\n",
    "    )\n",
    "\n",
    "    \n",
    "def execute(SQL, user):\n",
    "    start_time = time.time()  # запоминаем время начала выполнения функции\n",
    "    engine = get_engine(user)\n",
    "    Session = sessionmaker(bind=engine)  # sessions factory ()\n",
    "    with Session() as session: # open session\n",
    "        result = session.execute(text(SQL))\n",
    "        df = pd.DataFrame(result.fetchall(), columns=result.keys())\n",
    "        \n",
    "    end_time = time.time()  # запоминаем время окончания выполнения функции\n",
    "    execution_time = round(end_time - start_time,4) # вычисляем время выполнения   \n",
    "    \n",
    "    print(f\"Время выполнения функции: {execution_time} секунд\")\n",
    "    print()\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3500a90b-1a1a-449a-82f8-0e563ba2fa42",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import gspread\n",
    "from gspread_dataframe import get_as_dataframe\n",
    "from google.oauth2.service_account import Credentials\n",
    "import requests\n",
    "import xml.etree.ElementTree as ET\n",
    "from oauth2client.service_account import ServiceAccountCredentials"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb2241f6-afc6-4348-992a-d8a94ee7760b",
   "metadata": {},
   "source": [
    "# Код для прогрузки диапазона дат"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "52df9b0a-eb3e-49c1-b97c-acbab84c2a98",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Курс JPY на 01/11/2024: 0.632069\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 02/11/2024: 0.6389520000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 03/11/2024: 0.639671\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 04/11/2024: 0.639671\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 05/11/2024: 0.639671\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 06/11/2024: 0.64354\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 07/11/2024: 0.6443000000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 08/11/2024: 0.634364\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 09/11/2024: 0.638808\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 10/11/2024: 0.638808\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 11/11/2024: 0.638808\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 12/11/2024: 0.639811\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 13/11/2024: 0.636946\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 14/11/2024: 0.635027\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 15/11/2024: 0.636158\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 16/11/2024: 0.6396540000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 17/11/2024: 0.6396540000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 18/11/2024: 0.6396540000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 19/11/2024: 0.647719\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 20/11/2024: 0.6478100000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 21/11/2024: 0.647076\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 22/11/2024: 0.6493380000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 23/11/2024: 0.664353\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 24/11/2024: 0.664353\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 25/11/2024: 0.664353\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 26/11/2024: 0.673092\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 27/11/2024: 0.6835420000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 28/11/2024: 0.706643\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 29/11/2024: 0.722478\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 30/11/2024: 0.7182729999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 01/12/2024: 0.7182729999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 02/12/2024: 0.7182729999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 03/12/2024: 0.713601\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 04/12/2024: 0.708391\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 05/12/2024: 0.69329\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 06/12/2024: 0.687666\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 07/12/2024: 0.662898\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 08/12/2024: 0.662898\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 09/12/2024: 0.662898\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 10/12/2024: 0.663346\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 11/12/2024: 0.6602800000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 12/12/2024: 0.680308\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 13/12/2024: 0.682534\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 14/12/2024: 0.6764579999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 15/12/2024: 0.6764579999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 16/12/2024: 0.6764579999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 17/12/2024: 0.668784\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 18/12/2024: 0.667777\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 19/12/2024: 0.6685070000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 20/12/2024: 0.667877\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 21/12/2024: 0.648361\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 22/12/2024: 0.648361\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 23/12/2024: 0.648361\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 24/12/2024: 0.6486709999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 25/12/2024: 0.634597\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 26/12/2024: 0.633869\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 27/12/2024: 0.630149\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 28/12/2024: 0.636455\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 29/12/2024: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 30/12/2024: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 31/12/2024: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 01/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 02/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 03/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 04/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 05/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 06/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 07/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 08/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 09/01/2025: 0.643746\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 10/01/2025: 0.646063\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 11/01/2025: 0.6434000000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 12/01/2025: 0.6434000000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 13/01/2025: 0.6434000000000001\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 14/01/2025: 0.6484099999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 15/01/2025: 0.6565819999999999\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 16/01/2025: 0.650518\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 17/01/2025: 0.654747\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 18/01/2025: 0.660095\n",
      "Курс успешно записан в Google Sheets.\n",
      "Курс JPY на 19/01/2025: 0.660095\n",
      "Курс успешно записан в Google Sheets.\n"
     ]
    }
   ],
   "source": [
    "# # Функция для получения курса йены  \n",
    "# def get_jpy_rate(date):  \n",
    "#     formatted_date = date.strftime(\"%d/%m/%Y\")  \n",
    "#     url = f\"https://www.cbr.ru/scripts/XML_daily.asp?date_req={formatted_date}\"  \n",
    "#     response = requests.get(url)  \n",
    "#     response.raise_for_status()  \n",
    "    \n",
    "#     tree = ET.fromstring(response.content)  \n",
    "#     for currency in tree.findall('Valute'):  \n",
    "#         char_code = currency.find('CharCode').text  \n",
    "#         if char_code == \"JPY\":  \n",
    "#             rate = currency.find('Value').text   \n",
    "#             return float(rate.replace(',', '.')) / 100  # Преобразуем строку в число с плавающей запятой  \n",
    "#     return None  # Если курс не найден, возвращаем None  \n",
    "\n",
    "# def write_to_google_sheets(sheet_name, date, value):\n",
    "#     # Авторизация Google Sheets API\n",
    "#     scope = [\"https://spreadsheets.google.com/feeds\", \"https://www.googleapis.com/auth/drive\"]\n",
    "#     creds = ServiceAccountCredentials.from_json_keyfile_name(\"exchange-rate.json\", scope)\n",
    "#     client = gspread.authorize(creds)\n",
    "\n",
    "#     # Открытие нужного Google Sheets файла\n",
    "#     spreadsheet = client.open(sheet_name)\n",
    "    \n",
    "#     # Открытие листа по имени 'exchange_rate'\n",
    "#     sheet = spreadsheet.worksheet(\"exchange_rate\")\n",
    "    \n",
    "#     # Преобразование даты в формат 'YYYY-MM-DD'\n",
    "#     formatted_date = date.strftime(\"%Y-%m-%d\")\n",
    "#     sheet.append_row([formatted_date, value], value_input_option=\"USER_ENTERED\")\n",
    "\n",
    "\n",
    "# # Основной блок  \n",
    "# if __name__ == \"__main__\":  \n",
    "#     try:  \n",
    "#         start_date = datetime(2024, 11, 1)  # Начальная дата  \n",
    "#         end_date = datetime.now()  # Текущая дата  \n",
    "\n",
    "#         # Проходим по датам от 01/01/2025 до текущей даты  \n",
    "#         current_date = start_date  \n",
    "#         while current_date <= end_date:  \n",
    "#             jpy_rate = get_jpy_rate(current_date)  \n",
    "#             if jpy_rate is not None:  \n",
    "#                 print(f\"Курс JPY на {current_date.strftime('%d/%m/%Y')}: {jpy_rate}\")  \n",
    "#                 write_to_google_sheets(\"Japan_trip\", current_date, jpy_rate)  \n",
    "#                 print(\"Курс успешно записан в Google Sheets.\")  \n",
    "#             else:  \n",
    "#                 print(f\"Курс JPY на {current_date.strftime('%d/%m/%Y')} не найден.\")  \n",
    "#             current_date += timedelta(days=1)  # Переход к следующему дню  \n",
    "\n",
    "#     except Exception as e:  \n",
    "#         print(f\"Ошибка: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bdb98ceb-cd64-4496-bec2-b8c055c7792a",
   "metadata": {},
   "source": [
    "# Код для прогрузки текущей даты "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "9df88e64-7de9-4174-ad7f-e76891576f76",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Курс JPY на 19/01/2025: 0.660095\n",
      "Курс успешно записан в Google Sheets.\n"
     ]
    }
   ],
   "source": [
    "# Функция для получения курса йены  \n",
    "def get_jpy_rate(date):  \n",
    "    formatted_date = date.strftime(\"%d/%m/%Y\")  \n",
    "    url = f\"https://www.cbr.ru/scripts/XML_daily.asp?date_req={formatted_date}\"  \n",
    "    response = requests.get(url)  \n",
    "    response.raise_for_status()  \n",
    "    \n",
    "    # Разбор XML  \n",
    "    tree = ET.fromstring(response.content)  \n",
    "    for currency in tree.findall('Valute'):  \n",
    "        char_code = currency.find('CharCode').text  \n",
    "        if char_code == \"JPY\":  \n",
    "            rate = currency.find('Value').text   \n",
    "            return float(rate.replace(',', '.')) / 100  # Преобразуем строку в число с плавающей запятой  \n",
    "    return None  # Если курс не найден, возвращаем None  \n",
    "\n",
    "def write_to_google_sheets(sheet_name, date, value):  \n",
    "    # Авторизация Google Sheets API  \n",
    "    scope = [\"https://spreadsheets.google.com/feeds\", \"https://www.googleapis.com/auth/drive\"]  \n",
    "    creds = ServiceAccountCredentials.from_json_keyfile_name(\"exchange-rate.json\", scope)  \n",
    "    client = gspread.authorize(creds)  \n",
    "\n",
    "    # Открытие нужного Google Sheets файла  \n",
    "    spreadsheet = client.open(sheet_name)  \n",
    "    \n",
    "    # Открытие листа по имени 'exchange_rate'  \n",
    "    sheet = spreadsheet.worksheet(\"exchange_rate\")  \n",
    "    \n",
    "    # Преобразование даты в формат 'YYYY-MM-DD'  \n",
    "    formatted_date = date.strftime(\"%Y-%m-%d\")  \n",
    "    sheet.append_row([formatted_date, value], value_input_option=\"USER_ENTERED\")  \n",
    "\n",
    "# Основной блок  \n",
    "if __name__ == \"__main__\":  \n",
    "    try:  \n",
    "        today = datetime.now()  # Сегодняшняя дата  \n",
    "        jpy_rate = get_jpy_rate(today)  # Получение курса JPY  \n",
    "        \n",
    "        if jpy_rate is not None:  \n",
    "            print(f\"Курс JPY на {today.strftime('%d/%m/%Y')}: {jpy_rate}\")  \n",
    "            write_to_google_sheets(\"Japan_trip\", today, jpy_rate)  \n",
    "            print(\"Курс успешно записан в Google Sheets.\")  \n",
    "        else:  \n",
    "            print(f\"Курс JPY на {today.strftime('%d/%m/%Y')} не найден.\")  \n",
    "\n",
    "    except Exception as e:  \n",
    "        print(f\"Ошибка: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "89022f6e-d991-4bab-9ceb-69ea0f00366f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
